name: Jayi Daily Bots

on:
  schedule:
    - cron: '0 21 * * *' # KST 06:00
  workflow_dispatch:

jobs:
  run-bots:
    runs-on: ubuntu-latest
    env:
      # 루트 디렉토리를 파이썬 경로에 추가
      PYTHONPATH: ${{ github.workspace }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TG_ID: ${{ secrets.TG_ID }}
      TG_TOKEN_MARKET: ${{ secrets.TG_TOKEN_MARKET }}
      TG_TOKEN_AUCTION: ${{ secrets.TG_TOKEN_AUCTION }}
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Business Bot
        run: python -m bots.business_bot

      - name: Run Wealth Bot
        run: python -m bots.wealth_bot

      - name: Run Auction Bot
        run: python -m bots.auction_bot
